/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js projects and checked in here so the
// prototype type-checks before the first local Next build mutates the tree.
