// Tests for the shipped Part 450 workbook logic (web/js/part450.js). Same idea
// as sim.test.ts: exercise the exact module the static site loads. These stay
// deterministic and never assert an FAA numeric threshold — the workbook is an
// engineering tool, not a license application.
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import {
  CATALOG,
  FAILURES,
  HAZARDS,
  PART450_DISCLAIMER,
  REGULATORY_VALUE_REQUIRED,
  generateSafetyReport,
  runPart450Assessment
} from "../../web/js/part450.js";

const EXPECTED_DISCLAIMER =
  "STRIDE is an engineering analysis and research tool. Results generated by this module do not constitute FAA approval, a Part 450 license application, or an FAA-validated flight safety analysis.";

function readRegulatory(name: string): string {
  return readFileSync(resolve(process.cwd(), "regulatory/part450", name), "utf8");
}

describe("Part 450 workbook (web/js/part450.js)", () => {
  it("keeps the mandatory scope disclaimer verbatim", () => {
    expect(PART450_DISCLAIMER).toBe(EXPECTED_DISCLAIMER);
  });

  it("runs the example assessment with the expected shape", () => {
    const assessment = runPart450Assessment({ enabledIds: FAILURES.map((f) => f.id) });

    expect(assessment.hazards.length).toBe(HAZARDS.length);
    expect(assessment.failureRuns.length).toBe(FAILURES.length);
    expect(assessment.constraints.length).toBeGreaterThan(0);
    expect(assessment.nominal.outcome).toBe("landed");
    expect(assessment.risk.equation).toContain("P_failure");
    expect(assessment.risk.expectedCasualties).toBeGreaterThanOrEqual(0);
  });

  it("sums Ec exactly from the per-scenario product terms", () => {
    const assessment = runPart450Assessment({ enabledIds: FAILURES.map((f) => f.id) });
    for (const row of assessment.risk.contributions) {
      expect(row.ec).toBeCloseTo(row.pf * row.pImpact * row.pCas * row.n, 10);
    }
    const summed = assessment.risk.contributions.reduce((total, row) => total + row.ec, 0);
    expect(assessment.risk.expectedCasualties).toBeCloseTo(summed, 10);
  });

  it("is deterministic (same enabled failures → same risk numbers)", () => {
    const ids = FAILURES.map((f) => f.id);
    const a = runPart450Assessment({ enabledIds: ids });
    const b = runPart450Assessment({ enabledIds: ids });
    expect(a.risk.expectedCasualties).toBe(b.risk.expectedCasualties);
    expect(a.risk.individualRisk).toBe(b.risk.individualRisk);
  });

  it("reruns fewer scenarios when failures are disabled", () => {
    const subset = FAILURES.slice(0, 3).map((f) => f.id);
    const assessment = runPart450Assessment({ enabledIds: subset });
    expect(assessment.failureRuns.length).toBe(3);
  });

  it("never invents FAA numeric thresholds", () => {
    // Every public-risk criterion stays empty until criteria.yaml is filled in.
    expect(CATALOG.criteria.every((c) => c.threshold === null)).toBe(true);
    // Requirement citations stay flagged as placeholders.
    for (const req of CATALOG.requirements) {
      expect(req.id).toMatch(/^PART450-/);
      expect(req.citation).toContain("PLACEHOLDER");
    }
  });

  it("emits a report with the disclaimer and no fabricated limits", () => {
    const assessment = runPart450Assessment({ enabledIds: FAILURES.map((f) => f.id) });
    const report = generateSafetyReport(assessment);
    expect(report).toContain(EXPECTED_DISCLAIMER);
    expect(report).toContain("14 CFR Part 450");
    expect(report).toContain(REGULATORY_VALUE_REQUIRED);
    expect(report).toContain("## 12. Part 450 Compliance / Evidence Matrix");
  });

  it("mirrors the regulatory YAML catalog (ids present, thresholds empty)", () => {
    // web/js has no YAML parser (CSP / zero deps), so the JS CATALOG is a hand
    // maintained mirror of regulatory/part450/*.yaml. This guards the mirror
    // and enforces "no remembered FAA numbers".
    const requirementsYaml = readRegulatory("requirements.yaml");
    const criteriaYaml = readRegulatory("criteria.yaml");

    for (const req of CATALOG.requirements) {
      expect(requirementsYaml).toContain(req.id);
    }
    for (const criterion of CATALOG.criteria) {
      expect(criteriaYaml).toContain(`id: ${criterion.id}`);
    }
    // The YAML must not carry a numeric threshold either.
    expect(criteriaYaml).not.toMatch(/threshold:\s*[0-9]/);
  });
});
