/*
 * STRIDE Part 450 workbook — browser port.
 *
 * Same idea as lib/part450: Sea Turtle trajectories plus a hazard register,
 * off-nominal cases, a first-order footprint, conceptual Ec, and a
 * placeholder compliance matrix. No YAML parser here (CSP / no deps);
 * the catalog is a JS object that mirrors regulatory/part450/*.yaml.
 *
 * Not a license application. Not an FAA-validated FSA.
 */

import { runMasterSim, runTrackedEntry } from "./sim.js";

export const REGULATORY_VALUE_REQUIRED = "REGULATORY VALUE REQUIRED";

export const PART450_DISCLAIMER =
  "STRIDE is an engineering analysis and research tool. Results generated by this module do not constitute FAA approval, a Part 450 license application, or an FAA-validated flight safety analysis.";

export const CATALOG = {
  regulation: "14 CFR Part 450",
  unspecifiedDisplay: REGULATORY_VALUE_REQUIRED,
  requirements: [
    {
      id: "PART450-PLACEHOLDER-FLIGHT-SAFETY-ANALYSIS",
      citation: "14 CFR Part 450 — PLACEHOLDER: insert flight safety analysis section",
      title: "PLACEHOLDER: Flight safety analysis",
      tool: "Sea Turtle + this workbook",
      status: "ANALYSIS_COMPLETE",
    },
    {
      id: "PART450-PLACEHOLDER-PUBLIC-RISK",
      citation: "14 CFR Part 450 — PLACEHOLDER: insert public risk / expected casualty section",
      title: "PLACEHOLDER: Public risk criteria",
      tool: "web/js/part450.js risk sum",
      status: "ANALYSIS_COMPLETE",
    },
    {
      id: "PART450-PLACEHOLDER-HAZARD-ANALYSIS",
      citation: "14 CFR Part 450 — PLACEHOLDER: insert hazard analysis / system safety section",
      title: "PLACEHOLDER: Hazard analysis",
      tool: "hazard register",
      status: "ANALYSIS_COMPLETE",
    },
    {
      id: "PART450-PLACEHOLDER-FLIGHT-SAFETY-SYSTEM",
      citation: "14 CFR Part 450 — PLACEHOLDER: insert FSS / AFSS section",
      title: "PLACEHOLDER: Flight safety system",
      tool: "CONOPS flags only",
      status: "REQUIRES_EXTERNAL_EVIDENCE",
    },
    {
      id: "PART450-PLACEHOLDER-CONTAINMENT",
      citation: "14 CFR Part 450 — PLACEHOLDER: insert containment / hazard area section",
      title: "PLACEHOLDER: Debris containment and hazard areas",
      tool: "constraint checks",
      status: "ANALYSIS_COMPLETE",
    },
    {
      id: "PART450-PLACEHOLDER-TRAJECTORY-ANALYSIS",
      citation: "14 CFR Part 450 — PLACEHOLDER: insert trajectory analysis section",
      title: "PLACEHOLDER: Trajectory analysis",
      tool: "Sea Turtle (web/js/sim.js)",
      status: "ANALYSIS_COMPLETE",
    },
    {
      id: "PART450-PLACEHOLDER-APPLICATION-EVIDENCE",
      citation: "14 CFR Part 450 — PLACEHOLDER: insert application / compliance demonstration section",
      title: "PLACEHOLDER: Application evidence",
      tool: "markdown report download",
      status: "IN_WORK",
    },
  ],
  criteria: [
    { id: "expected_casualties", name: "Expected casualties (Ec)", quantity: "expected_casualties", threshold: null },
    { id: "individual_risk", name: "Individual risk", quantity: "individual_risk", threshold: null },
    { id: "collective_risk", name: "Collective risk", quantity: "collective_risk", threshold: null },
    { id: "aircraft_risk", name: "Aircraft risk", quantity: "aircraft_risk", threshold: null },
    { id: "maritime_risk", name: "Ship / maritime exposure", quantity: "maritime_risk", threshold: null },
  ],
};

export const MISSION = {
  id: "ex-leo-reentry-florida",
  name: "LEO reusable capsule reentry (example)",
  vehicleName: "STRIDE example reusable capsule",
  notes:
    "Example workflow: LEO → deorbit → entry interface → hypersonic entry → chute → recovery. Uses Sea Turtle for the trajectory and synthetic population for risk.",
  site: { name: "On-orbit / deorbit initiation (LEO)", lat: 28.47, lon: -80.57 },
  recovery: { name: "Synthetic Florida recovery area", lat: 28.47, lon: -80.57 },
  capabilities: {
    commandedTermination: false,
    autonomousFlightSafetySystem: false,
    notes: "Example CONOPS does not claim an FSS. Set the flags when a real design has one.",
  },
  cfg: {
    missionName: "STRIDE_LEO_reusable_reentry",
    payloadMassKg: 2800,
    startAltKm: 120,
    startVelMps: 7650,
    entryAngleDeg: 3.75,
    targetLat: 28.47,
    targetLon: -80.57,
    tpsDensity: 480,
    tpsThickness: 0.06,
    chuteCd: 1.8,
    shieldCd: 1.15,
    chuteDeployAltM: 6000,
    shockFactorX: 1.6,
    testShieldDiams: [3.6],
    testChuteDiams: [14],
  },
  vehicle: { shieldDiameterM: 3.6, chuteDiameterM: 14 },
};

export const HAZARDS = [
  ["HAZ-PROP-001", "Propulsion failure during deorbit", "deorbit", "critical", "open"],
  ["HAZ-PROP-002", "Loss of thrust", "deorbit", "critical", "open"],
  ["HAZ-PROP-003", "Unintended thrust", "exoatmospheric", "catastrophic", "open"],
  ["HAZ-GNC-001", "GNC failure", "hypersonic_entry", "catastrophic", "open"],
  ["HAZ-GNC-002", "Loss of attitude control", "hypersonic_entry", "catastrophic", "open"],
  ["HAZ-STR-001", "Structural breakup", "hypersonic_entry", "catastrophic", "open"],
  ["HAZ-TPS-001", "Thermal protection failure", "hypersonic_entry", "catastrophic", "open"],
  ["HAZ-SEP-001", "Stage / separation failure", "terminal_descent", "critical", "open"],
  ["HAZ-NAV-001", "Navigation error", "deorbit", "major", "watching"],
  ["HAZ-COM-001", "Communication loss", "hypersonic_entry", "major", "open"],
  ["HAZ-FSS-001", "Flight safety system failure", "hypersonic_entry", "catastrophic", "open"],
  ["HAZ-REC-001", "Parachute / recovery failure", "terminal_descent", "critical", "watching"],
  ["HAZ-REC-002", "Landing outside the designated recovery area", "recovery", "major", "watching"],
].map(([id, description, phase, severity, status]) => ({
  id,
  description,
  phase,
  severity,
  status,
}));

export const FAILURES = [
  {
    id: "FAIL-CHUTE",
    name: "Recovery system failure (no parachute)",
    failureType: "recovery_system_failure",
    probability: 0.02,
    changes: { chuteEnabled: false },
  },
  {
    id: "FAIL-CD-HI",
    name: "Aero Cd +15%",
    failureType: "aero_coefficient_uncertainty",
    probability: 0.08,
    changes: { shieldCdScale: 1.15 },
  },
  {
    id: "FAIL-CD-LO",
    name: "Aero Cd −15%",
    failureType: "aero_coefficient_uncertainty",
    probability: 0.08,
    changes: { shieldCdScale: 0.85 },
  },
  {
    id: "FAIL-STEEP",
    name: "Late / steep deorbit (entry angle +1°)",
    failureType: "late_maneuver",
    probability: 0.03,
    changes: { entryAngleDeltaDeg: 1 },
  },
  {
    id: "FAIL-SHALLOW",
    name: "Early / shallow deorbit (entry angle −0.8°)",
    failureType: "early_maneuver",
    probability: 0.03,
    changes: { entryAngleDeltaDeg: -0.8 },
  },
  {
    id: "FAIL-NAV",
    name: "Guidance / navigation bias",
    failureType: "guidance_failure",
    probability: 0.04,
    changes: { crossrangeRateMps: 18 },
  },
  {
    id: "FAIL-TVC",
    name: "Thrust vector / pointing error",
    failureType: "thrust_vector_error",
    probability: 0.02,
    changes: { crossrangeRateMps: -12, entryAngleDeltaDeg: 0.4 },
  },
  {
    id: "FAIL-LOC",
    name: "Loss of control at peak heating",
    failureType: "loss_of_control",
    probability: 0.015,
    changes: { gammaKickDeg: 2.5, crossrangeRateMps: 25, atPeakHeat: true },
  },
  {
    id: "FAIL-BALLISTIC",
    name: "Ballistic continuation (already no-lift)",
    failureType: "ballistic_continuation",
    probability: 0.05,
    changes: {},
  },
];

const KEEP_OUT = [
  { lat: 28.9, lon: -81.6 },
  { lat: 28.9, lon: -81.05 },
  { lat: 27.9, lon: -81.05 },
  { lat: 27.9, lon: -81.6 },
];

function haversineKm(lat1, lon1, lat2, lon2) {
  const R = 6371;
  const p1 = (lat1 * Math.PI) / 180;
  const p2 = (lat2 * Math.PI) / 180;
  const dp = ((lat2 - lat1) * Math.PI) / 180;
  const dl = ((lon2 - lon1) * Math.PI) / 180;
  const a =
    Math.sin(dp / 2) ** 2 + Math.cos(p1) * Math.cos(p2) * Math.sin(dl / 2) ** 2;
  return 2 * R * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}

function pointInPolygon(lat, lon, polygon) {
  let inside = false;
  for (let i = 0, j = polygon.length - 1; i < polygon.length; j = i, i += 1) {
    const yi = polygon[i].lat;
    const xi = polygon[i].lon;
    const yj = polygon[j].lat;
    const xj = polygon[j].lon;
    const intersect =
      yi > lat !== yj > lat && lon < ((xj - xi) * (lat - yi)) / (yj - yi + 1e-18) + xi;
    if (intersect) inside = !inside;
  }
  return inside;
}

function sampleAtPeak(samples, key) {
  let best = samples[0];
  for (const s of samples) {
    if ((s[key] ?? 0) > (best?.[key] ?? 0)) best = s;
  }
  return best;
}

function applyChanges(baseCfg, vehicle, changes, startLon) {
  const opts = {
    shieldDiameterM: vehicle.shieldDiameterM,
    chuteDiameterM: vehicle.chuteDiameterM,
    startLongitudeDeg: startLon,
    skipTargeting: true,
    chuteEnabled: changes.chuteEnabled !== false,
    shieldCd: (changes.shieldCdScale ?? 1) * baseCfg.shieldCd,
    crossrangeRateMps: changes.crossrangeRateMps ?? 0,
    entryAngleDeg: Math.max(0.1, baseCfg.entryAngleDeg + (changes.entryAngleDeltaDeg ?? 0)),
  };
  if (changes.chuteEnabled === false) opts.chuteEnabled = false;
  return opts;
}

function conceptualCasualtyProbability(ke) {
  // Placeholder lethality vs KE. Not an FAA casualty-area model.
  if (ke < 50) return 0.001;
  if (ke < 1_000) return 0.01;
  if (ke < 50_000) return 0.05;
  if (ke < 1_000_000) return 0.15;
  return 0.35;
}

function syntheticPopulation() {
  const cells = [];
  for (let lat = 26.5; lat <= 30.5; lat += 0.5) {
    for (let lon = -82.5; lon <= -79.0; lon += 0.5) {
      const inland = lon > -81.0 && lat > 27.2 && lat < 29.8;
      const coastal = lon > -81.4 && lon <= -80.3;
      const ocean = lon <= -80.4 && !inland;
      let people = 40;
      if (inland) people = 18000;
      else if (coastal) people = 6500;
      if (ocean) people = 12;
      if (Math.abs(lat - 28.4) < 0.3 && Math.abs(lon - -80.6) < 0.3) people = 22000;
      cells.push({ lat, lon, people });
    }
  }
  return cells;
}

function nExposed(cells, lat, lon, radiusKm) {
  let n = 0;
  for (const cell of cells) {
    if (haversineKm(lat, lon, cell.lat, cell.lon) <= radiusKm) n += cell.people;
  }
  if (n > 0) return n;
  // Fall back to the 0.5° cell that contains the impact (same idea as the TS workbook).
  const hit = cells.find((cell) => Math.abs(cell.lat - lat) <= 0.25 && Math.abs(cell.lon - lon) <= 0.25);
  return hit?.people ?? 0;
}

function circleLatLon(lat, lon, radiusKm, steps = 64) {
  const points = [];
  const d = radiusKm / 6371;
  const lat1 = (lat * Math.PI) / 180;
  const lon1 = (lon * Math.PI) / 180;
  for (let i = 0; i <= steps; i += 1) {
    const brng = (2 * Math.PI * i) / steps;
    const lat2 = Math.asin(
      Math.sin(lat1) * Math.cos(d) + Math.cos(lat1) * Math.sin(d) * Math.cos(brng),
    );
    const lon2 =
      lon1 +
      Math.atan2(
        Math.sin(brng) * Math.sin(d) * Math.cos(lat1),
        Math.cos(d) - Math.sin(lat1) * Math.sin(lat2),
      );
    points.push({ lat: (lat2 * 180) / Math.PI, lon: (lon2 * 180) / Math.PI });
  }
  return points;
}

function mulberry32(seed) {
  let t = seed >>> 0;
  return () => {
    t += 0x6d2b79f5;
    let r = Math.imul(t ^ (t >>> 15), 1 | t);
    r ^= r + Math.imul(r ^ (r >>> 7), 61 | r);
    return ((r ^ (r >>> 14)) >>> 0) / 4294967296;
  };
}

function debrisFrom(nominal) {
  const peak = sampleAtPeak(nominal.samples, "qDyn") ?? nominal.samples.at(-1);
  const recipes = [
    { id: "DEB-CORE", massFrac: 0.55, dia: 1.5, cd: 1.1 },
    { id: "DEB-TPS", massFrac: 0.2, dia: 1.8, cd: 1.4 },
    { id: "DEB-TANK", massFrac: 0.15, dia: 1.1, cd: 0.8 },
    { id: "DEB-MISC", massFrac: 0.1, dia: 0.7, cd: 1.2 },
  ];
  const impacts = recipes.map((recipe) => {
    const mass = (nominal.massKg ?? 2800) * recipe.massFrac;
    const result = runMasterSim(
      { ...MISSION.cfg, payloadMassKg: Math.max(mass - 5, 0.1), shieldCd: recipe.cd },
      recipe.dia,
      recipe.dia,
      MISSION.cfg.entryAngleDeg,
      {
        track: true,
        maxSamples: 180,
        chuteEnabled: false,
        shieldCd: recipe.cd,
        startLongitudeDeg: nominal.deorbitLongitudeDeg,
        skipTargeting: true,
        initialState: {
          h: peak.h,
          v: peak.v,
          gamma: (peak.gammaDeg * Math.PI) / 180,
          t: peak.t,
          rangeM: peak.rangeM,
          crossrangeM: peak.crossrangeM,
          mass,
        },
      },
    );
    return {
      id: recipe.id,
      lat: result.impactLatitudeDeg,
      lon: result.impactLongitudeDeg,
      v: result.impactVelocityMs,
      ke: result.impactKineticEnergyJ,
    };
  });
  return { impacts, peak };
}

function constraintHits(run, nominal) {
  const impact = run.samples.at(-1);
  if (!impact) return [];
  const hits = [];
  const rec = MISSION.recovery;
  const dRec = haversineKm(impact.lat, impact.lon, rec.lat, rec.lon);
  if (dRec > 40) hits.push("CON-RECOVERY");
  if (dRec > 120) hits.push("CON-CONTAIN");
  let leftCorridor = false;
  for (const s of run.samples) {
    let best = Infinity;
    for (const n of nominal.samples) {
      const d = haversineKm(s.lat, s.lon, n.lat, n.lon);
      if (d < best) best = d;
    }
    if (best > 75) {
      leftCorridor = true;
      break;
    }
  }
  if (leftCorridor) hits.push("CON-CORRIDOR");
  if (run.samples.some((s) => pointInPolygon(s.lat, s.lon, KEEP_OUT))) {
    hits.push("CON-KEEPOUT");
  }
  return hits;
}

/**
 * Run the example LEO reentry safety workbook.
 * enabledIds: which FAILURES to include. monteCarlo: optional Cd scatter.
 */
export function runPart450Assessment({ enabledIds, monteCarlo = false } = {}) {
  const cfg = MISSION.cfg;
  const vehicle = MISSION.vehicle;
  const nominal = runTrackedEntry(cfg, {
    shieldDiameterM: vehicle.shieldDiameterM,
    chuteDiameterM: vehicle.chuteDiameterM,
  });

  const selected = FAILURES.filter((f) => !enabledIds || enabledIds.includes(f.id));
  const failureRuns = selected.map((scenario) => {
    const opts = applyChanges(cfg, vehicle, scenario.changes, nominal.deorbitLongitudeDeg);
    if (scenario.changes.atPeakHeat && nominal.samples.length) {
      const peak = sampleAtPeak(nominal.samples, "qDyn");
      opts.initialState = {
        h: peak.h,
        v: peak.v,
        gamma: ((peak.gammaDeg + (scenario.changes.gammaKickDeg ?? 0)) * Math.PI) / 180,
        t: peak.t,
        rangeM: peak.rangeM,
        crossrangeM: peak.crossrangeM,
      };
    }
    const trajectory = runTrackedEntry(cfg, opts);
    return { scenario, trajectory, hits: constraintHits(trajectory, nominal) };
  });

  const debris = debrisFrom(nominal);
  if (monteCarlo) {
    const rand = mulberry32(450);
    for (let i = 0; i < 12; i += 1) {
      const u1 = Math.max(rand(), 1e-9);
      const u2 = rand();
      const z = Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2);
      const scale = Math.max(0.5, 1 + 0.08 * z);
      const run = runTrackedEntry(cfg, {
        shieldDiameterM: vehicle.shieldDiameterM,
        chuteDiameterM: vehicle.chuteDiameterM,
        startLongitudeDeg: nominal.deorbitLongitudeDeg,
        skipTargeting: true,
        shieldCd: cfg.shieldCd * scale,
      });
      debris.impacts.push({
        id: `MC-${i}`,
        lat: run.impactLatitudeDeg,
        lon: run.impactLongitudeDeg,
        v: run.impactVelocityMs,
        ke: run.impactKineticEnergyJ,
      });
    }
  }

  const pop = syntheticPopulation();
  const contributions = failureRuns.map((run) => {
    const pImpact = run.trajectory.outcome === "landed" ? 1 : 0.25;
    const pCas = conceptualCasualtyProbability(run.trajectory.impactKineticEnergyJ);
    const n = nExposed(
      pop,
      run.trajectory.impactLatitudeDeg,
      run.trajectory.impactLongitudeDeg,
      5,
    );
    const ec = run.scenario.probability * pImpact * pCas * n;
    return { id: run.scenario.id, pf: run.scenario.probability, pImpact, pCas, n, ec };
  });
  const expectedCasualties = contributions.reduce((s, row) => s + row.ec, 0);

  let individualRisk = 0;
  for (const cell of pop) {
    let p = 0;
    for (const run of failureRuns) {
      const d = haversineKm(
        cell.lat,
        cell.lon,
        run.trajectory.impactLatitudeDeg,
        run.trajectory.impactLongitudeDeg,
      );
      if (d <= 5) {
        p +=
          run.scenario.probability *
          conceptualCasualtyProbability(run.trajectory.impactKineticEnergyJ);
      }
    }
    if (p > individualRisk) individualRisk = p;
  }

  const uniqueHits = new Set(failureRuns.flatMap((run) => run.hits));
  uniqueHits.delete("CON-AFSS");

  const constraints = [
    { id: "CON-RECOVERY", name: "Designated recovery zone", kind: "recovery_zone" },
    { id: "CON-CORRIDOR", name: "Allowable trajectory corridor", kind: "trajectory_corridor" },
    { id: "CON-KEEPOUT", name: "Synthetic inland keep-out", kind: "keep_out" },
    { id: "CON-CONTAIN", name: "Impact containment region", kind: "impact_containment" },
    { id: "CON-AFSS", name: "Autonomous flight safety rule (geometry TBD)", kind: "autonomous_flight_safety" },
  ].map((c) => ({
    ...c,
    violated: uniqueHits.has(c.id),
  }));

  return {
    mission: MISSION,
    catalog: CATALOG,
    nominal,
    hazards: HAZARDS,
    failureRuns,
    debris,
    risk: {
      equation: "Ec = Σ(P_failure × P_impact × P_casualty × N_exposed)",
      expectedCasualties,
      individualRisk,
      collectiveRisk: expectedCasualties,
      contributions,
    },
    constraints,
    recoveryCircle: circleLatLon(MISSION.recovery.lat, MISSION.recovery.lon, 40),
    keepOut: KEEP_OUT,
    generatedAtIso: new Date().toISOString(),
  };
}

export function generateSafetyReport(assessment) {
  const { mission, nominal, hazards, failureRuns, debris, risk, constraints } = assessment;
  const lines = [
    "# STRIDE Part 450 Mission Safety Assessment",
    "",
    `_Generated ${assessment.generatedAtIso}_`,
    "",
    `**${PART450_DISCLAIMER}**`,
    "",
    `Mission: **${mission.name}**`,
    "",
    "## 1. Mission Overview",
    "",
    mission.notes,
    "",
    "## 2. Vehicle Description",
    "",
    mission.vehicleName,
    "",
    "## 3. Concept of Operations",
    "",
    "LEO → deorbit → entry interface → hypersonic entry → chute → recovery.",
    "",
    "## 4. Nominal Trajectory",
    "",
    `- Outcome: ${nominal.outcome}`,
    `- Range: ${nominal.rangeKm.toFixed(1)} km`,
    `- Impact: ${nominal.impactLatitudeDeg.toFixed(3)}, ${nominal.impactLongitudeDeg.toFixed(3)}`,
    `- Peak G: ${nominal.g.toFixed(2)}`,
    "",
    "## 5. Hazard Analysis",
    "",
  ];
  for (const h of hazards) {
    lines.push(`- ${h.id}: ${h.description} (${h.severity}, ${h.status})`);
  }
  lines.push("", "## 6. Failure Scenarios", "");
  for (const run of failureRuns) {
    const s = run.trajectory;
    lines.push(
      `- ${run.scenario.id} (${run.scenario.failureType}, P_f=${run.scenario.probability}): ${s.outcome} at ${s.impactLatitudeDeg.toFixed(2)}, ${s.impactLongitudeDeg.toFixed(2)}`,
    );
  }
  lines.push(
    "",
    "## 7. Flight Safety Analysis",
    "",
    "Off-nominal Sea Turtle reruns. Not a 6-DOF Monte Carlo FSA.",
    "",
    "## 8. Debris / Impact Analysis",
    "",
    "Conceptual / preliminary debris model. Not an FAA-validated breakup analysis.",
    "",
  );
  for (const imp of debris.impacts) {
    lines.push(`- ${imp.id}: ${imp.lat.toFixed(2)}, ${imp.lon.toFixed(2)}  V=${imp.v.toFixed(1)} m/s`);
  }
  lines.push(
    "",
    "## 9. Public Risk Assessment",
    "",
    `Equation: \`${risk.equation}\``,
    `- Conceptual Ec: ${risk.expectedCasualties.toExponential(3)}`,
    `- Individual risk (max cell): ${risk.individualRisk.toExponential(3)}`,
    `- Aircraft / maritime: NOT IMPLEMENTED`,
    `- Thresholds: ${REGULATORY_VALUE_REQUIRED}`,
    "",
    "## 10. Flight Safety Constraints",
    "",
  );
  for (const c of constraints) {
    lines.push(`- ${c.id} ${c.name}: ${c.violated ? "VIOLATED on at least one run" : "clear on plotted runs"}`);
  }
  lines.push(
    "",
    "## 11. Assumptions and Limitations",
    "",
    "- Planar 2-DOF no-lift Sea Turtle model.",
    "- Synthetic population. Nothing is downloaded.",
    "- P_casualty vs kinetic energy is a placeholder curve.",
    "- Example P_f values are independent and may overlap; the Ec sum is conceptual bookkeeping and can double-count, not a mutually-exclusive event decomposition.",
    `- ${PART450_DISCLAIMER}`,
    "",
    "## 12. Part 450 Compliance / Evidence Matrix",
    "",
  );
  for (const req of CATALOG.requirements) {
    lines.push(`- ${req.citation} — ${req.title} — ${req.status}`);
  }
  lines.push(
    "",
    "## 13. Open Items / Required External Analyses",
    "",
    "- Authoritative Part 450 citations in regulatory/part450/.",
    "- Validated debris / casualty-area methodology.",
    "- Real population, airports, airways, maritime traffic.",
    "",
    "---",
    "",
    PART450_DISCLAIMER,
    "",
  );
  return lines.join("\n");
}