import { parse } from "yaml";
import {
  BUNDLED_APPLICABILITY_YAML,
  BUNDLED_CRITERIA_YAML,
  BUNDLED_REQUIREMENTS_YAML
} from "./regulatory/bundledYaml";

export const REGULATORY_VALUE_REQUIRED = "REGULATORY VALUE REQUIRED";

export const PART450_DISCLAIMER =
  "STRIDE is an engineering analysis and research tool. Results generated by this module do not constitute FAA approval, a Part 450 license application, or an FAA-validated flight safety analysis.";

export interface RegulatoryProvenance {
  citation: string;
  source: string;
  effectiveDate: string | null;
  revision: string;
  verificationDate: string | null;
}

export interface RequirementRecord extends RegulatoryProvenance {
  id: string;
  title: string;
  requirementText: string;
  notes: string | null;
}

export interface CriterionRecord extends RegulatoryProvenance {
  id: string;
  name: string;
  quantity: string;
  threshold: number | null;
  units: string;
  notes: string | null;
}

export interface OperationApplicability {
  id: string;
  label: string;
  defaultApplicableRequirementIds: string[];
}

export interface Part450Catalog {
  regulation: string;
  unspecifiedDisplay: string;
  disclaimer: string;
  requirements: RequirementRecord[];
  criteria: CriterionRecord[];
  operations: OperationApplicability[];
}

interface RequirementsFile {
  schema_version: number;
  regulation: string;
  disclaimer: string;
  entries: Array<{
    id: string;
    citation: string;
    title: string;
    requirement_text: string;
    source: string;
    effective_date: string | null;
    revision: string;
    verification_date: string | null;
    notes: string | null;
  }>;
}

interface CriteriaFile {
  schema_version: number;
  regulation: string;
  disclaimer: string;
  unspecified_display: string;
  criteria: Array<{
    id: string;
    name: string;
    quantity: string;
    threshold: number | null;
    units: string;
    citation: string;
    source: string;
    effective_date: string | null;
    revision: string;
    verification_date: string | null;
    notes: string | null;
  }>;
}

interface ApplicabilityFile {
  schema_version: number;
  operations: Array<{
    id: string;
    label: string;
    default_applicable_requirement_ids: string[];
  }>;
}

export function parseRequirementsYaml(text: string): RequirementRecord[] {
  const parsed = parse(text) as RequirementsFile;
  if (!parsed?.entries?.length) {
    throw new Error("requirements.yaml: no entries");
  }
  return parsed.entries.map((entry) => ({
    id: entry.id,
    title: entry.title,
    requirementText: entry.requirement_text,
    notes: entry.notes ?? null,
    citation: entry.citation,
    source: entry.source,
    effectiveDate: entry.effective_date,
    revision: entry.revision,
    verificationDate: entry.verification_date
  }));
}

export function parseCriteriaYaml(text: string): { unspecifiedDisplay: string; criteria: CriterionRecord[] } {
  const parsed = parse(text) as CriteriaFile;
  if (!parsed?.criteria?.length) {
    throw new Error("criteria.yaml: no criteria");
  }
  return {
    unspecifiedDisplay: parsed.unspecified_display || REGULATORY_VALUE_REQUIRED,
    criteria: parsed.criteria.map((entry) => ({
      id: entry.id,
      name: entry.name,
      quantity: entry.quantity,
      threshold: entry.threshold,
      units: entry.units,
      notes: entry.notes ?? null,
      citation: entry.citation,
      source: entry.source,
      effectiveDate: entry.effective_date,
      revision: entry.revision,
      verificationDate: entry.verification_date
    }))
  };
}

export function parseApplicabilityYaml(text: string): OperationApplicability[] {
  const parsed = parse(text) as ApplicabilityFile;
  if (!parsed?.operations?.length) {
    throw new Error("applicability.yaml: no operations");
  }
  return parsed.operations.map((entry) => ({
    id: entry.id,
    label: entry.label,
    defaultApplicableRequirementIds: entry.default_applicable_requirement_ids
  }));
}

export function loadPart450Catalog(sources?: {
  requirementsYaml?: string;
  criteriaYaml?: string;
  applicabilityYaml?: string;
}): Part450Catalog {
  const requirements = parseRequirementsYaml(sources?.requirementsYaml ?? BUNDLED_REQUIREMENTS_YAML);
  const criteriaFile = parseCriteriaYaml(sources?.criteriaYaml ?? BUNDLED_CRITERIA_YAML);
  const operations = parseApplicabilityYaml(sources?.applicabilityYaml ?? BUNDLED_APPLICABILITY_YAML);

  return {
    regulation: "14 CFR Part 450",
    unspecifiedDisplay: criteriaFile.unspecifiedDisplay,
    disclaimer: PART450_DISCLAIMER,
    requirements,
    criteria: criteriaFile.criteria,
    operations
  };
}

export function formatThreshold(criterion: CriterionRecord, unspecifiedDisplay = REGULATORY_VALUE_REQUIRED): string {
  if (criterion.threshold === null || Number.isNaN(criterion.threshold)) {
    return unspecifiedDisplay;
  }
  return String(criterion.threshold);
}

export function findRequirement(catalog: Part450Catalog, id: string): RequirementRecord | undefined {
  return catalog.requirements.find((entry) => entry.id === id);
}

export function findCriterion(catalog: Part450Catalog, id: string): CriterionRecord | undefined {
  return catalog.criteria.find((entry) => entry.id === id);
}
